const data = {
  eventProducts: [
    {
      id: '1',
      title: 'Event1',
      event: 'Kids Outing',
      image: './images/rsz_kids.jpg',

      description: 'sdfgcnjk',
      restriction: 'None',
      where: 'Groningen',
      when: '12-12-22',
      price: 15.0,
      available: 'Available',
    },
    {
      id: '2',
      title: 'Event2',
      event: 'Dance Party',
      image: './images/rsz_login.jpg',
      text: 'Kids outing',
      description: 'nnn',
      restriction: '18plus',
      where: 'Rotterdam',
      when: '25-12-22',
      price: 20.0,
      available: 'Sold Out',
    },
    {
      id: '3',
      title: 'Event 3',
      event: 'Bachata',
      image: 'images/upcomingevent4.jpg',
      description: 'ghvjbbii',
      restriction: 'None',
      where: 'Heerlen',
      when: '22-11-22',
      price: 0,
      available: 'Available',
    },
    {
      id: '4',
      title: 'Event 4',
      event: 'Show your moves',
      image: 'images/events4.jpg',
      description: 'bbbbbbbbbbb',
      restriction: 'None',
      where: 'Hoensbroek',
      when: '23-10-22',
      price: 5.0,
      // available: 'Available',
    },
    {
      id: '5',
      title: 'Event 5',
      event: 'Zumba',
      image: 'images/rsz_zumba.jpg',
      description: 'vhhhhhhhh',
      restriction: 'None',
      where: 'Delft',
      when: '23-01-22',
      price: 12.0,
      available: 'Available',
    },
    {
      id: '6',
      title: 'Event 6',
      event: 'Camping',
      image: 'images/campfire.jpg',
      description: 'Ffghhjj bbnm',
      restriction: 'None',
      where: 'Eindhoven',
      when: '23-01-22',
      price: 12.0,
      available: 'Available',
    },
  ],
};
export default data;

/* const products = [
  {
    id: '1',
    title: 'Event1',
    event: 'Kids Outing',
    image: '../../images/rsz_kids.jpg',

    description: 'sdfgcnjk',
    restriction: 'None',
    where: 'Groningen',
    when: '12-12-22',
    price: 15.0,
    available: 'Available',
  },
  {
    id: '2',
    title: 'Event2',
    event: 'Dance Party',
    image: '../../images/events3.jpg',
    text: 'Kids outing',
    description: 'nnn',
    restriction: '18plus',
    where: 'Rotterdam',
    when: '25-12-22',
    price: 20.0,
    available: 'Sold Out',
  },
  {
    id: '3',
    title: 'Event 3',
    event: 'Bachata',
    image: '../../images/upcomingevent4.jpg',
    description: 'ghvjbbii',
    restriction: 'None',
    where: 'Heerlen',
    when: '22-11-22',
    price: 0,
    available: 'Available',
  },
  {
    id: '4',
    title: 'Event 4',
    event: 'Show your moves',
    image: '../../images/events4.jpg',
    description: 'bbbbbbbbbbb',
    restriction: 'None',
    where: 'Hoensbroek',
    when: '23-10-22',
    price: 5.0,
    available: 'Available',
  },
  {
    id: '5',
    title: 'Event 5',
    event: 'Zumba',
    image: '../../images/rsz_zumba.jpg',
    description: 'vhhhhhhhh',
    restriction: 'None',
    where: 'Delft',
    when: '23-01-22',
    price: 12.0,
    available: 'Available',
  },
];
export default products;
 */
